--ROL
CREATE TABLE ROL(
	ID_ROL INT,
	NOMBRE_ROL VARCHAR(20),
	CONSTRAINT PK_ID_ROL PRIMARY KEY(ID_ROL)
);

--USUARIO
CREATE TABLE USUARIO(
	ID_USUARIO INT,
	RUT_USUARIO VARCHAR(15),
	CONTRASEÑA VARCHAR(10),
	NOMBRE_USUARIO VARCHAR(30),
	APELLIDO1_USUARIO VARCHAR(30),
	APELLIDO2_USUARIO VARCHAR(30),
	DIRECCION VARCHAR(50),
	ID_ROL INT,
	CONSTRAINT PK_USUARIO PRIMARY KEY(ID_USUARIO),
	CONSTRAINT FK_USUARIO_ROL FOREIGN KEY(ID_ROL) REFERENCES ROL(ID_ROL)
);

--CATEGORIAS
CREATE TABLE CATEGORIAS(
	ID_CATEGORIA INT,
	NOMBRE_CATEGORIA VARCHAR(20),
	ESTADO_CATEGORIA BOOLEAN,
	CONSTRAINT PK_CATEGORIAS PRIMARY KEY(ID_CATEGORIA)
);

--PRODUCTOS
CREATE TABLE PRODUCTOS(
	COD_PRODUCTO INT,
	NOMBRE_PRODUCTO VARCHAR(20),
	PRECIO_PRODUCTO INT,
	CANTIDAD_TOTAL INT,
	CANTIDAD_DISPONIBLE INT,
	DESCRIPCION_PRODUCTO VARCHAR(200), 
	IMAGEN BYTEA, --BINARY
	ID_CATEGORIA INT,
	CONSTRAINT PK_PRODUCTOS PRIMARY KEY(COD_PRODUCTO),
	CONSTRAINT FK_PRODUCTOS_CATEGORIAS FOREIGN KEY(ID_CATEGORIA) REFERENCES CATEGORIAS(ID_CATEGORIA)
);

--CARRITO 
CREATE TABLE CARRITO(
	ID_CARRO INT,
	ID_USUARIO INT,
	SUBTOTAL INT,
	TOTAL INT,
	CONSTRAINT PK_CARRITO PRIMARY KEY(ID_CARRO),
	CONSTRAINT FK_CARRITO_USUARIO FOREIGN KEY(ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
);

--CARRITO PRODUCTOS
CREATE TABLE CARRITO_PRODUCTOS(
	ID_CARRO_PRODUCTOS INT,
	COD_PRODUCTO INT,
	CANTIDAD INT, 
	ID_CARRO INT,
	CONSTRAINT PK_CARRITO_PRODUCTOS PRIMARY KEY(ID_CARRO_PRODUCTOS),
	CONSTRAINT FK_CARRITO_PRODUCTOS_PRODUCTOS FOREIGN KEY(COD_PRODUCTO) REFERENCES PRODUCTOS(COD_PRODUCTO),
	CONSTRAINT FK_CARRITO_PRODUCTOS_CARRITO FOREIGN KEY(ID_CARRO) REFERENCES CARRITO(ID_CARRO)
);

--VENTAS
CREATE TABLE VENTAS(
	ID_VENTA INT,
	ID_USUARIO INT,
	FECHA_VENTA DATE,
	SUBTOTAL INT,
	IMPUESTOS INT,
	DESCUENTOS INT,
	TOTAL INT,
	METODO_DE_PAGO VARCHAR(15),
	ESTADO_DE_LA_VENTA BOOLEAN, 
	CONSTRAINT PK_VENTAS PRIMARY KEY(ID_VENTA),
	CONSTRAINT FK_VENTAS_USUARIO FOREIGN KEY(ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
);

--VENTAS_PRODUCTOS
CREATE TABLE VENTAS_PRODUCTOS(
	ID_VENTAS_PRODUCTOS INT,
	ID_VENTA INT,
	COD_PRODUCTO INT,
	CANTIDAD INT,
	CONSTRAINT PK_VENTAS_PRODUCTOS PRIMARY KEY(ID_VENTAS_PRODUCTOS),
	CONSTRAINT FK_VENTAS_PRODUCTOS_VENTAS FOREIGN KEY(ID_VENTA) REFERENCES VENTAS(ID_VENTA),
	CONSTRAINT FK_VENTAS_PRODUCTOS_PRODUCTOS FOREIGN KEY(COD_PRODUCTO) REFERENCES PRODUCTOS(COD_PRODUCTO)
);

--PEDIDOS PERSONALIZADOS 
CREATE TABLE PEDIDOS_PERSONALIZADOS(
	ID_PEDIDO INT, 
	DESCRIPCION VARCHAR(200),
	IMAGEN BYTEA, --BINARIO
	ID_CATEGORIA INT,
	ID_USUARIO INT,
	CONSTRAINT PK_PEDIDOS_PERSONALIZADOS PRIMARY KEY(ID_PEDIDO),
	CONSTRAINT FK_PEDIDOS_PERSONALIZADOS_CATEGORIAS FOREIGN KEY(ID_CATEGORIA) REFERENCES CATEGORIAS(ID_CATEGORIA),
	CONSTRAINT FK_PEDIDOS_PERSONALIZADOS_USUARIO FOREIGN KEY(ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
);
